// <auto-generated />
namespace CMDLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sort_parentInfo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sort_parentInfo));
        
        string IMigrationMetadata.Id
        {
            get { return "201609051833346_sort_parentInfo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
