// <auto-generated />
namespace CMDLogic.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Sort_ManyToMany_EntityKind : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Sort_ManyToMany_EntityKind));
        
        string IMigrationMetadata.Id
        {
            get { return "201609051759206_Sort_ManyToMany_EntityKind"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
